# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yadir-vega

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crpersonalportfolio.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_abf8d165655b49b891cb08034497e7e0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cf34dd6889d149a0bf5b2f70b155b32f }}

    - name: Convertir nombre de usuario a minúsculas
      run: echo "USERNAME_LOWER=$(echo ${{ secrets.AzureAppService_ContainerUsername_abf8d165655b49b891cb08034497e7e0 }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crpersonalportfolio.azurecr.io/${{ env.USERNAME_LOWER }}/yvega-portfolio:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yadir-vega'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d8da62798b6c4344a57a8de3caf318a8 }}
        images: 'crpersonalportfolio.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abf8d165655b49b891cb08034497e7e0 }}/yvega-portfolio:${{ github.sha }}'